apiVersion: v1
kind: Service
metadata:
  name: stocks-app
  namespace: project-3-cloud
spec:
  type: ClusterIP
  selector:
    app: stocks-app 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
