apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: project-3-cloud
spec:
  selector:
    app: capital-gains-service 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: ClusterIP